spring:
  application:
    name: library_system
  datasource:
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
